name: desafio_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_crashlytics: ^2.8.2
  cloud_firestore: ^3.1.18
  get: 4.6.5
  dartz: 0.10.1
  flutter_phosphor_icons: 0.0.1+6
  shimmer: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

